//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultView1
    {
        public string 学号 { get; set; }
        public string 姓名 { get; set; }
        public Nullable<int> 成绩 { get; set; }
        public string 科目名称 { get; set; }
    }
}
