//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Result = new HashSet<Result>();
        }
    
        public string StudentNo { get; set; }
        public string LoginPwd { get; set; }
        public string StudentName { get; set; }
        public string Sex { get; set; }
        public int GradeId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BornDate { get; set; }
        public string Email { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual ICollection<Result> Result { get; set; }
    }
}
